[project]
name = "BroBot"
version = "1.1.0"
requires-python = ">= 3.10"
authors = [
  {name = "Jose Alarcon", email = "jose@example.com"}
]
description = "A workout helper."
license = {text = "MIT License"}
readme = "readme.md"

[project.scripts]
brobot = "brobot.console:run"
